apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dia-app
    auther: Hemendra
    country: IN
  name: dia-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dia-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dia-app
        auther: Hemendra
        country: IN
    spec:
      containers:
      - image: hemendra05/diabetes-model
        name: diabetes-model
        resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dia-app
    auther: hemendra
    country: IN
  name: dia-app
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: dia-app
  type: NodePort
status:
  loadBalancer: {}
